image: $SKA_K8S_TOOLS_DOCKER_BUILDER_IMAGE

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  # Ensure TEST_INGRESS is defined so that we don't try to evaluate `minikube ip` in the Makefile
  TEST_INGRESS: ""
  CI_POETRY_VERSION: 1.8.2

# Enable caching for python
cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .cache/pip

stages:
  - build
  - pre-test
  - test
  - post-test
  - lint
  - publish
  - pages
  - scan

# Include CI templates
include:
    # Python
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/python.gitlab-ci.yml'

    # Docs pages
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/docs.gitlab-ci.yml'

    # Tag Based GitLab Release Management
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/release.gitlab-ci.yml'

    # Build and push the docker image
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/oci-image.gitlab-ci.yml'

    # Build and push the Helm chart
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/helm-chart.gitlab-ci.yml'

    # Test Helm chart
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/k8s-test.gitlab-ci.yml'

    # .post step finalisers eg: badges
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/finaliser.gitlab-ci.yml'

oci-image-build-keycloak:
  extends:
    - .image_builder_template
  stage: build
  variables:
    OCI_IMAGE: ska-data-lifecycle-test-keycloak
    OCI_IMAGE_FILE_PATH: tests/Dockerfile-keycloak
  script:
    make oci-build-keycloak CAR_OCI_REGISTRY_HOST=${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}

oci-image-build-gateway:
  extends:
    - .image_builder_template
  stage: build
  variables:
    OCI_IMAGE: ska-data-lifecycle-test-gateway
    OCI_IMAGE_FILE_PATH: tests/Dockerfile-gateway
  script:
    make oci-build-gateway CAR_OCI_REGISTRY_HOST=${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}

python-test:
  image: docker:27.0.2
  services:
    - docker:27.0.2-dind
  before_script:
    - docker compose --file tests/testrunner.docker-compose.yaml build
  script:
    - docker compose --file tests/testrunner.docker-compose.yaml -p dlm-test-services run dlm_testrunner .
  after_script:
    - docker compose --file tests/testrunner.docker-compose.yaml -p dlm-test-services down

k8s-test:
  variables:
    KUBE_NAMESPACE: ci-$CI_PROJECT_NAME-$CI_PIPELINE_ID
    HELM_VALUES: resources/initialised-dlm.yaml
  before_script:
    - poetry self update $CI_POETRY_VERSION
    - poetry config virtualenvs.create $POETRY_CONFIG_VIRTUALENVS_CREATE
    - poetry install --with=test
  script:
    - make k8s-install-chart
    - make k8s-test
  environment:
    action: access
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: manual
      allow_failure: true
    - if: $CI_PIPELINE_SOURCE == "push"
      when: manual
      allow_failure: true
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: always
