version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    post_create_environment:
      - curl -sSL https://install.python-poetry.org | python3 - --version 1.3.2
      - $HOME/.local/bin/poetry config virtualenvs.create false
    post_install:
      - $HOME/.local/bin/poetry install --only main,docs

sphinx:
  configuration: docs/src/conf.py
  fail_on_warning: true
