FROM python:3.10

RUN pip install --extra-index-url https://artefact.skao.int/repository/pypi-internal/simple ska-sdp-config
RUN pip install --extra-index-url https://artefact.skao.int/repository/pypi-internal/simple ska-ser-logging
RUN pip install --extra-index-url https://artefact.skao.int/repository/pypi-internal/simple ska-sdp-dataproduct-metadata
RUN pip install --extra-index-url https://artefact.skao.int/repository/pypi-internal/simple ska_sdp_metadata_generator

RUN mkdir -p /data
RUN apt-get update && apt-get install -y 
RUN apt-get install -y python3-casacore rclone iputils-ping 

WORKDIR /app
COPY ./ ./

RUN pip install pytest requests_mock kubernetes docker
RUN pip install --extra-index-url https://artefact.skao.int/repository/pypi-internal/simple /app/.

ENTRYPOINT pytest --env docker tests/integration/test_ska_data_lifecycle.py
