# pylint: disable=R0912
"""Heuristic implementations for DLM data lifecycle management.

NOTE: Generated by copilot from OID_phase_enforce sequence diagram.

PROMPT: Use this sequence diagram to create python code with a abstract
class for heuristics and the OID Phase heuristics as one implementation.
"""

# pylint: disable=too-few-public-methods
# pylint: disable=arguments-differ
# pylint: disable=invalid-name
# pylint: disable=too-many-locals
# pylint: disable=broad-exception-caught
# pylint: disable=too-many-return-statements

from abc import ABC, abstractmethod
from typing import List, Optional
from uuid import UUID

from sqlalchemy import func, select, update
from sqlalchemy.ext.asyncio import AsyncSession

from ska_dlm.common_types import ItemState, PhaseType
from ska_dlm.dlm_db.models import DataItem, Storage
from ska_dlm.dlm_storage import dlm_storage_requests

# Phase hierarchy by resilience: higher number = higher resilience
# Order from lowest to highest resilience: PLASMA, GAS, LIQUID, SOLID
PHASE_ORDER = {
    PhaseType.PLASMA: 0,  # Lowest resilience
    PhaseType.GAS: 1,
    PhaseType.LIQUID: 2,
    PhaseType.SOLID: 3,  # Highest resilience
}


class HeuristicResult:
    """Result of a heuristic execution."""

    def __init__(self, success: bool, message: str = "", data: Optional[dict] = None):
        self.success = success
        self.message = message
        self.data = data or {}


class BaseHeuristic(ABC):
    """Abstract base class for all heuristics."""

    def __init__(self, session: AsyncSession):
        self.session = session

    @abstractmethod
    async def execute(self, **kwargs) -> HeuristicResult:
        """Execute the heuristic logic.

        Args
        ----
        kwargs : dict
            Heuristic-specific parameters

        Returns
        -------
        HeuristicResult
            The result of the heuristic execution
        """

    @classmethod
    def success_result(cls, message: str = "", data: Optional[dict] = None) -> HeuristicResult:
        """Create a successful heuristic result.

        Args
        ----
        message : str
            Optional success message
        data : Optional[dict]
            Optional data dictionary

        Returns
        -------
        HeuristicResult
            HeuristicResult with success=True
        """
        return HeuristicResult(True, message, data)


class CombineUidPhasesHeuristic(BaseHeuristic):
    """Heuristic to combine UID phases into a single actual phase."""

    async def execute(self, uid_phases: List[PhaseType]) -> HeuristicResult:
        """Combine UID phases to determine the actual phase for an OID.

        The logic here is to take the highest phase among all UIDs.
        Phase hierarchy: PLASMA < GAS < LIQUID < SOLID
        TODO: This implementation is worst case and does not cover the
        actual combination of multiple lower phases.

        Args
        ----
        uid_phases : List[PhaseType]
            List of UID phases

        Returns
        -------
        HeuristicResult
            HeuristicResult with the combined actual phase
        """
        if not uid_phases:
            return HeuristicResult(False, "No UID phases provided")

        n_SOLID = uid_phases.count(PhaseType.SOLID)
        n_LIQUID = uid_phases.count(PhaseType.LIQUID)
        n_GAS = uid_phases.count(PhaseType.GAS)
        n_PLASMA = uid_phases.count(PhaseType.PLASMA)
        # PLASMA does not really count for any resilience, even if combined
        if n_PLASMA == len(uid_phases):
            actual_phase = PhaseType.PLASMA
        elif n_SOLID >= 1:
            # if it is already SOLID we can't get any better anyway
            actual_phase = PhaseType.SOLID
        elif n_LIQUID >= 2 or n_GAS >= 3 or (n_LIQUID == 1 and n_GAS >= 2):
            actual_phase = PhaseType.SOLID
        elif (n_LIQUID == 1 and n_GAS <= 1) or (n_LIQUID == 0 and n_GAS == 2):
            actual_phase = PhaseType.LIQUID
        else:
            actual_phase = PhaseType.GAS

        return self.success_result(
            f"Combined phase: {actual_phase}", {"actual_phase": actual_phase}
        )


class ChangeOidPhaseHeuristic(BaseHeuristic):
    """Heuristic to change the OID phase based on the change_oid_phase sequence diagram.

    This heuristic implements the logic to transition an OID from its current phase
    to a target phase by either deleting UID instances (to reduce resilience) or
    creating additional UID instances (to increase resilience).
    """

    def __init__(self, session: AsyncSession):
        super().__init__(session)
        self.combine_heuristic = CombineUidPhasesHeuristic(session)
        self.delete_heuristic = DeleteUidHeuristic(session)

    async def execute(self, oid: UUID, target_phase: PhaseType = None) -> HeuristicResult:
        """Execute the change OID phase heuristic according to the sequence diagram.

        Steps:
        1. Query OID and get all UIDs with their phases
        2. Combine UID phases to get ACTUAL_PHASE
        3. Compare target_phase with ACTUAL_PHASE:
           - If target_phase requires higher resilience (lower PHASE_ORDER):  # noqa: RST301
             Delete UIDs until result_phase == target_phase  # noqa: RST301
           - If target_phase requires lower resilience (higher PHASE_ORDER):  # noqa: RST301
             Create additional UID instances  # noqa: RST301

        4. Update OID_phase to target_phase
        5. Return status

        Args
        ----
        oid : UUID
            The OID to change the phase for
        target_phase : PhaseType, optional
            Target phase to reach. If not provided, uses target_phase from database

        Returns
        -------
        HeuristicResult
            HeuristicResult indicating success/failure
        """
        try:
            # Step 1: Query OID data to get target_phase if not provided
            stmt = select(DataItem).where(DataItem.OID == oid)
            result = await self.session.execute(stmt)
            data_item = result.scalar()

            if not data_item:
                return HeuristicResult(False, f"No data found for OID {oid}")

            # Use provided target_phase or get from database
            if target_phase is None:
                target_phase = data_item.target_phase

            current_phase = data_item.OID_phase

            # Step 1.5: Query all UIDs for this OID
            uid_stmt = select(Storage.storage_phase, DataItem.UID).where(
                DataItem.OID == oid,
                DataItem.deleted.is_(False),
                DataItem.storage_id == Storage.storage_id,
            )
            uid_result = await self.session.execute(uid_stmt)
            uid_rows = uid_result.fetchall()
            uid_phases = [row[0] for row in uid_rows]
            all_uids = [row[1] for row in uid_rows]

            if not uid_phases:
                return HeuristicResult(False, f"No UIDs found for OID {oid}")

            # Step 2: Combine UID phases to get ACTUAL_PHASE
            combine_result = await self.combine_heuristic.execute(uid_phases)
            if not combine_result.success:
                return combine_result

            actual_phase = combine_result.data["actual_phase"]

            # Step 3: Compare phases and take appropriate action
            target_order = PHASE_ORDER.get(target_phase, float("inf"))
            actual_order = PHASE_ORDER.get(actual_phase, float("inf"))

            # Case 1: target_phase requires lower resilience (lower order) than actual_phase
            if target_order < actual_order:
                # Need to delete UIDs to reduce redundancy/reach lower resilience
                deletion_results = []
                current_result_phase = actual_phase

                for uid in all_uids:
                    if current_result_phase == target_phase:
                        break

                    delete_result = await self.delete_heuristic.execute(uid)
                    deletion_results.append(
                        {
                            "uid": uid,
                            "success": delete_result.success,
                            "message": delete_result.message,
                        }
                    )

                    if delete_result.success and "result_phase" in delete_result.data:
                        current_result_phase = delete_result.data["result_phase"]
                    elif not delete_result.success:
                        # Stop attempting deletions if one fails
                        break

                if current_result_phase != target_phase:
                    return HeuristicResult(
                        False,
                        f"Failed to reach target phase {target_phase}; "
                        f"reached {current_result_phase}",
                        {"deletion_results": deletion_results},
                    )

                # Update OID_phase to target_phase
                update_stmt = (
                    update(DataItem).where(DataItem.OID == oid).values(OID_phase=target_phase)
                )
                await self.session.execute(update_stmt)
                await self.session.commit()

                return self.success_result(
                    f"Deleted UID instances to reach OID {oid} target phase {target_phase}",
                    {
                        "oid": oid,
                        "target_phase": target_phase,
                        "result_phase": current_result_phase,
                        "deletion_results": deletion_results,
                    },
                )

            # Case 2: target_phase requires higher resilience (higher order) than actual_phase
            if target_order > actual_order:
                # Need to create additional UID instances to increase resilience
                # This requires selecting appropriate storage and copying data
                # Implementation deferred: would call data replication logic
                return HeuristicResult(
                    False,
                    f"Creating additional UID instances for OID {oid} not yet implemented. "
                    f"Current phase {actual_phase} vs target {target_phase}",
                )

            # Case 3: phases match
            # Update OID_phase if needed
            if current_phase != actual_phase:
                update_stmt = (
                    update(DataItem).where(DataItem.OID == oid).values(OID_phase=actual_phase)
                )
                await self.session.execute(update_stmt)
                await self.session.commit()

            return self.success_result(
                f"OID {oid} already at target phase {target_phase}",
                {
                    "oid": oid,
                    "target_phase": target_phase,
                    "current_phase": actual_phase,
                },
            )

        except Exception as exc:
            await self.session.rollback()
            return HeuristicResult(
                False, f"Error executing Change OID Phase heuristic: {str(exc)}"
            )


class DeleteUidHeuristic(BaseHeuristic):
    """Heuristic to safely delete a UID payload while preserving OID resilience."""

    def __init__(self, session: AsyncSession):
        super().__init__(session)
        self.combine_heuristic = CombineUidPhasesHeuristic(session)

    async def execute(self, uid: UUID) -> HeuristicResult:
        """Execute UID deletion heuristic according to deletion sequence diagram.

        Steps:
        1. Query UID entry and resolve OID
        2. Query other UID phases for OID
        3. Determine result phase if UID removed
        4. Reject if result phase < target phase
        5. Delete payload from storage
        6. Mark UID deleted + update OID phase

        Args
        ----
        uid : UUID
            The UID to delete

        Returns
        -------
        HeuristicResult
            HeuristicResult
        """
        try:
            # Step 1: Fetch target UID to get OID
            stmt = select(DataItem).where(DataItem.UID == uid)
            result = await self.session.execute(stmt)
            data_item = result.scalar()

            if not data_item:
                return HeuristicResult(False, f"No data found for UID {uid}")

            if not data_item.OID:
                return HeuristicResult(False, f"UID {uid} has no associated OID")

            oid = data_item.OID
            target_phase = data_item.target_phase

            # Step 2: Fetch other UIDs for same OID that are not already deleted
            uid_stmt = select(Storage.storage_phase, DataItem.UID).where(
                DataItem.OID == oid,
                DataItem.deleted.is_(False),
                DataItem.storage_id == Storage.storage_id,
            )
            uid_result = await self.session.execute(uid_stmt)
            remaining_rows = [r for r in uid_result.fetchall() if r[1] != uid]
            remaining_phases = [r[0] for r in remaining_rows]

            if remaining_phases:
                combine_result = await self.combine_heuristic.execute(remaining_phases)
                if not combine_result.success:
                    return combine_result
                # Step 2: Get resulting phase after deletion
                result_phase = combine_result.data["actual_phase"]
            else:
                # No remaining replicas; resilience phase reduces to GAS
                result_phase = PhaseType.GAS

            if PHASE_ORDER[result_phase] < PHASE_ORDER[target_phase]:
                # Here we could try to create another copy by
                # calling the IncreaseOidPhaseHeuristic, once implemented
                return HeuristicResult(
                    False,
                    "Deletion would violate resilience policy",
                    {
                        "oid": oid,
                        "uid": uid,
                        "result_phase": result_phase,
                        "target_phase": target_phase,
                    },
                )

            # Delete payload from storage manager
            if not dlm_storage_requests.delete_data_item_payload(str(uid)):
                return HeuristicResult(False, f"Failed to delete payload for UID {uid}")

            # Update UID metadata
            update_uid_stmt = (
                update(DataItem)
                .where(DataItem.UID == uid)
                .values(
                    item_state=ItemState.DELETED,
                    deleted=True,
                    UID_deletion=func.now(),  # pylint: disable=not-callable
                )
            )
            await self.session.execute(update_uid_stmt)

            # Update OID phase for the OID group
            update_oid_stmt = (
                update(DataItem).where(DataItem.OID == oid).values(OID_phase=result_phase)
            )
            await self.session.execute(update_oid_stmt)

            await self.session.commit()

            return self.success_result(
                f"Deleted UID {uid} payload and updated OID {oid} phase to {result_phase}",
                {"uid": uid, "oid": oid, "result_phase": result_phase},
            )

        except Exception as exc:
            # Any other exception: roll back
            await self.session.rollback()
            return HeuristicResult(False, f"Error executing UID deletion heuristic: {str(exc)}")


class UidExpiryHeuristic(BaseHeuristic):
    """Heuristic to discover expired UIDs and delegate deletion."""

    def __init__(self, session: AsyncSession):
        super().__init__(session)
        self.delete_heuristic = DeleteUidHeuristic(session)

    async def execute(self) -> HeuristicResult:
        """Execute the UID expiry heuristic.

        The heuristic discovers any UIDs whose expiration timestamp has passed,
        then delegates their cleanup to the delete heuristic.

        Returns
        -------
        HeuristicResult
            The result of the expiry scan and delegated deletions.
        """
        try:
            stmt = select(DataItem.UID).where(
                DataItem.UID_expiration < func.now(),  # pylint: disable=not-callable
                DataItem.deleted.is_(False),
            )
            result = await self.session.execute(stmt)
            expired_rows = result.fetchall()
            expired_uids = [row[0] for row in expired_rows]

            if not expired_uids:
                return self.success_result("No expired UIDs found", {"expired_uids": []})

            deletion_results = []
            for uid in expired_uids:
                delete_result = await self.delete_heuristic.execute(uid)
                deletion_results.append(
                    {
                        "uid": uid,
                        "success": delete_result.success,
                        "message": delete_result.message,
                    }
                )

            success = all(item["success"] for item in deletion_results)
            message = "Deleted expired UIDs" if success else "Some expired UID deletions failed"

            return HeuristicResult(
                success,
                message,
                {"expired_uids": expired_uids, "deletion_results": deletion_results},
            )

        except Exception as exc:
            await self.session.rollback()
            return HeuristicResult(False, f"Error executing UID expiry heuristic: {str(exc)}")


class OidExpiryHeuristic(BaseHeuristic):
    """Heuristic to discover expired OIDs and delete their UIDs."""

    def __init__(self, session: AsyncSession):
        super().__init__(session)
        self.delete_heuristic = DeleteUidHeuristic(session)

    async def execute(self) -> HeuristicResult:
        """Execute the OID expiry heuristic.

        The heuristic discovers any expired OIDs and delegates deletion of their
        associated UIDs to the delete heuristic.

        Returns
        -------
        HeuristicResult
            The result of the OID expiry scan and delegated UID deletions.
        """
        try:
            stmt = (
                select(DataItem.OID)
                .distinct()
                .where(
                    DataItem.OID_expiration < func.now(),  # pylint: disable=not-callable
                    DataItem.deleted.is_(False),
                    DataItem.OID.is_not(None),
                )
            )
            result = await self.session.execute(stmt)
            expired_rows = result.fetchall()
            expired_oids = [row[0] for row in expired_rows]

            if not expired_oids:
                return self.success_result("No expired OIDs found", {"expired_oids": []})

            deletion_results = []
            for oid in expired_oids:
                uid_stmt = select(DataItem.UID).where(
                    DataItem.OID == oid,
                    DataItem.deleted.is_(False),
                )
                uid_result = await self.session.execute(uid_stmt)
                uid_rows = uid_result.fetchall()
                for uid_row in uid_rows:
                    uid = uid_row[0]
                    delete_result = await self.delete_heuristic.execute(uid)
                    deletion_results.append(
                        {
                            "oid": oid,
                            "uid": uid,
                            "success": delete_result.success,
                            "message": delete_result.message,
                        }
                    )

            success = all(item["success"] for item in deletion_results)
            message = "Deleted expired OIDs" if success else "Some expired OID deletions failed"

            return HeuristicResult(
                success,
                message,
                {"expired_oids": expired_oids, "deletion_results": deletion_results},
            )

        except Exception as exc:
            await self.session.rollback()
            return HeuristicResult(False, f"Error executing OID expiry heuristic: {str(exc)}")


class OidPhaseEnforceHeuristic(BaseHeuristic):
    """Heuristic to enforce OID phase consistency with UID phases and target phase."""

    def __init__(self, session: AsyncSession):
        super().__init__(session)
        self.combine_heuristic = CombineUidPhasesHeuristic(session)
        self.increase_heuristic = IncreaseOidPhaseHeuristic(session)
        self.decrease_heuristic = DecreaseOidPhaseHeuristic(session)

    async def execute(self, oid: UUID) -> HeuristicResult:
        """Execute the OID Phase Enforce heuristic.

        This heuristic:
        1. Queries the database for OID phase, UID phases, and target phase
        2. Combines UID phases to get actual phase
        3. Compares phases and takes appropriate action:
        - If target_phase == actual_phase and OID_phase != actual_phase: update OID_phase
        - If target_phase < actual_phase: call increase heuristic
        - If target_phase > actual_phase: call decrease heuristic

        Args
        ----
        oid : UUID
            The OID to enforce phase consistency for

        Returns
        -------
        HeuristicResult
            The result of the heuristic execution
        """
        try:
            # Query OID and UID phases
            stmt = select(DataItem).where(DataItem.OID == oid)

            result = await self.session.execute(stmt)
            data_item = result.scalar()

            if not data_item:
                return HeuristicResult(False, f"No data found for OID {oid}")

            oid_phase = data_item.OID_phase
            target_phase = data_item.target_phase

            # Query all UID phases for this OID
            uid_stmt = select(Storage.storage_phase).where(
                DataItem.OID == oid, DataItem.storage_id == Storage.storage_id
            )
            uid_result = await self.session.execute(uid_stmt)
            uid_phases = [row[0] for row in uid_result.fetchall()]

            # Combine UID phases
            combine_result = await self.combine_heuristic.execute(uid_phases)
            if not combine_result.success:
                return combine_result

            actual_phase = combine_result.data["actual_phase"]

            # Decision logic
            if target_phase == actual_phase and oid_phase != actual_phase:
                # Update OID phase to match actual phase
                # Query all data items with this OID and update their OID_phase
                update_stmt = (
                    update(DataItem).where(DataItem.OID == oid).values(OID_phase=actual_phase)
                )
                await self.session.execute(update_stmt)
                await self.session.commit()
                return self.success_result(f"Updated OID {oid} phase to {actual_phase}")

            if PHASE_ORDER.get(target_phase, float("inf")) < PHASE_ORDER.get(
                actual_phase, float("inf")
            ):
                # Target phase has lower resilience than actual phase - need to decrease
                decrease_result = await self.decrease_heuristic.execute(
                    oid, oid_phase, target_phase
                )
                return decrease_result

            if PHASE_ORDER.get(target_phase, float("inf")) > PHASE_ORDER.get(
                actual_phase, float("inf")
            ):
                # Target phase has higher resilience than actual phase - need to increase
                increase_result = await self.increase_heuristic.execute(
                    oid, oid_phase, target_phase
                )
                return increase_result

            # Phases are consistent
            return self.success_result(f"OID {oid} phases are consistent")

        except Exception as e:
            await self.session.rollback()
            return HeuristicResult(False, f"Error executing OID Phase Enforce heuristic: {str(e)}")


class IncreaseOidPhaseHeuristic(BaseHeuristic):
    """Heuristic to increase OID phase resilience by creating additional UID instances.

    This heuristic creates additional copies of an OID in different storage backends
    to increase the overall resilience (move towards higher-resilience phases).
    """

    def __init__(self, session: AsyncSession):
        super().__init__(session)
        self.combine_heuristic = CombineUidPhasesHeuristic(session)

    async def execute(
        self, oid: UUID, current_phase: PhaseType, target_phase: PhaseType
    ) -> HeuristicResult:
        """Execute the increase OID phase heuristic.

        Creates additional UID instances to increase system resilience.

        Args
        ----
        oid : UUID
            The OID to increase phase resilience for
        current_phase : PhaseType
            Current OID phase
        target_phase : PhaseType
            Target phase to reach (must have higher resilience than current)

        Returns
        -------
        HeuristicResult
            Result of the heuristic execution
        """
        try:
            if PHASE_ORDER.get(target_phase, float("inf")) <= PHASE_ORDER.get(
                current_phase, float("inf")
            ):
                return HeuristicResult(
                    False,
                    f"Target phase {target_phase} does not provide higher resilience than "
                    f"current phase {current_phase}",
                )

            # TODO: Implementation requires:
            # 1. Query available storage backends with appropriate phases
            # 2. Select optimal storage for replication
            # 3. Create new DataItem/UID with copy of the data
            # 4. Trigger data replication via dlm_migration.copy_data_item()
            # 5. Update OID_phase once new copy reaches target phase
            # 6. Monitor replication status

            return HeuristicResult(
                False,
                f"Creating additional UID instances for OID {oid} to reach phase {target_phase} "
                f"is not yet fully implemented; requires data replication infrastructure",
            )

        except Exception as e:
            await self.session.rollback()
            return HeuristicResult(
                False, f"Error executing Increase OID Phase heuristic: {str(e)}"
            )


class DecreaseOidPhaseHeuristic(BaseHeuristic):
    """Heuristic to decrease OID phase resilience by deleting UID instances.

    This heuristic removes copies of an OID from storage to decrease the overall
    resilience (move towards lower-resilience phases like GAS or PLASMA).
    """

    def __init__(self, session: AsyncSession):
        super().__init__(session)
        self.delete_heuristic = DeleteUidHeuristic(session)
        self.combine_heuristic = CombineUidPhasesHeuristic(session)

    async def execute(
        self, oid: UUID, current_phase: PhaseType, target_phase: PhaseType
    ) -> HeuristicResult:
        """Execute the decrease OID phase heuristic.

        Deletes UID instances to decrease system resilience.

        Args
        ----
        oid : UUID
            The OID to decrease phase resilience for
        current_phase : PhaseType
            Current OID phase
        target_phase : PhaseType
            Target phase to reach (must have lower resilience than current)

        Returns
        -------
        HeuristicResult
            Result of the heuristic execution
        """
        try:
            if PHASE_ORDER.get(target_phase, float("inf")) >= PHASE_ORDER.get(
                current_phase, float("inf")
            ):
                return HeuristicResult(
                    False,
                    f"Target phase {target_phase} does not provide lower resilience than "
                    f"current phase {current_phase}",
                )

            # Query all UIDs for this OID
            uid_stmt = select(DataItem.UID).where(
                DataItem.OID == oid,
                DataItem.deleted.is_(False),
            )
            uid_result = await self.session.execute(uid_stmt)
            all_uids = [row[0] for row in uid_result.fetchall()]

            if not all_uids:
                return HeuristicResult(False, f"No UIDs found for OID {oid}")

            # Delete UIDs until we reach target phase
            deletion_results = []
            for uid in all_uids:
                delete_result = await self.delete_heuristic.execute(uid)
                deletion_results.append(
                    {
                        "uid": uid,
                        "success": delete_result.success,
                        "message": delete_result.message,
                    }
                )

                if delete_result.success:
                    # Check current phase
                    uid_stmt = select(DataItem.OID_phase).where(DataItem.UID == uid)
                    phase_result = await self.session.execute(uid_stmt)
                    phase_row = phase_result.scalar()

                    if phase_row == target_phase:
                        break
                elif not delete_result.success:
                    # Stop on first failure
                    break

            # Query current phase to verify
            current_stmt = select(DataItem.OID_phase).where(DataItem.OID == oid)
            current_result = await self.session.execute(current_stmt)
            current_phase_result = current_result.scalar()

            if current_phase_result == target_phase:
                return self.success_result(
                    f"Successfully decreased OID {oid} phase to {target_phase}",
                    {
                        "oid": oid,
                        "target_phase": target_phase,
                        "deletion_results": deletion_results,
                    },
                )
            return HeuristicResult(
                False,
                f"Failed to reach target phase {target_phase}; "
                f"current phase is {current_phase_result}",
                {"deletion_results": deletion_results},
            )

        except Exception as e:
            await self.session.rollback()
            return HeuristicResult(
                False, f"Error executing Decrease OID Phase heuristic: {str(e)}"
            )
