"""Heuristic implementations for DLM data lifecycle management.

NOTE: Generated by copilot from OID_phase_enforce sequence diagram.

PROMPT: Use this sequence diagram to create python code with a abstract
class for heuristics and the OID Phase heuristics as one implementation.
"""

# pylint: disable=too-few-public-methods
# pylint: disable=arguments-differ
# pylint: disable=invalid-name
# pylint: disable=too-many-locals
# pylint: disable=broad-exception-caught
# pylint: disable=too-many-return-statements

from abc import ABC, abstractmethod
from typing import List, Optional
from uuid import UUID

from sqlalchemy import func, select, update
from sqlalchemy.ext.asyncio import AsyncSession

from ska_dlm.common_types import ItemState, PhaseType
from ska_dlm.dlm_db.models import DataItem
from ska_dlm.dlm_storage import dlm_storage_requests

# Phase hierarchy by resilience: lower number = higher resilience
# Order from lowest to highest resilience: PLASMA, GAS, LIQUID, SOLID
PHASE_ORDER = {
    PhaseType.SOLID: 0,  # Highest resilience
    PhaseType.LIQUID: 1,
    PhaseType.GAS: 2,
    PhaseType.PLASMA: 3,  # Lowest resilience
}


class HeuristicResult:
    """Result of a heuristic execution."""

    def __init__(self, success: bool, message: str = "", data: Optional[dict] = None):
        self.success = success
        self.message = message
        self.data = data or {}


class BaseHeuristic(ABC):
    """Abstract base class for all heuristics."""

    def __init__(self, session: AsyncSession):
        self.session = session

    @abstractmethod
    async def execute(self, **kwargs) -> HeuristicResult:
        """Execute the heuristic logic.

        Args
        ----
        kwargs : dict
            Heuristic-specific parameters

        Returns
        -------
        HeuristicResult
            The result of the heuristic execution
        """

    @classmethod
    def success_result(cls, message: str = "", data: Optional[dict] = None) -> HeuristicResult:
        """Create a successful heuristic result.

        Args
        ----
        message : str
            Optional success message
        data : Optional[dict]
            Optional data dictionary

        Returns
        -------
        HeuristicResult
            HeuristicResult with success=True
        """
        return HeuristicResult(True, message, data)


class CombineUidPhasesHeuristic(BaseHeuristic):
    """Heuristic to combine UID phases into a single actual phase."""

    async def execute(self, uid_phases: List[PhaseType]) -> HeuristicResult:
        """Combine UID phases to determine the actual phase for an OID.

        The logic here is to take the highest phase among all UIDs.
        Phase hierarchy: PLASMA < GAS < LIQUID < SOLID
        TODO: This implementation is worst case and does not cover the
        actual combination of multiple lower phases.

        Args
        ----
        uid_phases : List[PhaseType]
            List of UID phases

        Returns
        -------
        HeuristicResult
            HeuristicResult with the combined actual phase
        """
        if not uid_phases:
            return HeuristicResult(False, "No UID phases provided")

        n_SOLID = uid_phases.count(PhaseType.SOLID)
        n_LIQUID = uid_phases.count(PhaseType.LIQUID)
        n_GAS = uid_phases.count(PhaseType.GAS)
        n_PLASMA = uid_phases.count(PhaseType.PLASMA)
        # PLASMA does not really count for any resilience, even if combined
        if n_PLASMA == len(uid_phases):
            actual_phase = PhaseType.PLASMA
        elif n_SOLID >= 1:
            # if it is already SOLID we can't get any better anyway
            actual_phase = PhaseType.SOLID
        elif n_LIQUID >= 2 or n_GAS >= 3 or (n_LIQUID == 1 and n_GAS >= 2):
            actual_phase = PhaseType.SOLID
        elif (n_LIQUID == 1 and n_GAS <= 1) or (n_LIQUID == 0 and n_GAS == 2):
            actual_phase = PhaseType.LIQUID
        else:
            actual_phase = PhaseType.GAS

        return self.success_result(
            f"Combined phase: {actual_phase}", {"actual_phase": actual_phase}
        )


class IncreaseOidPhaseHeuristic(BaseHeuristic):
    """Heuristic to increase the OID phase."""

    async def execute(
        self, oid: UUID, current_phase: PhaseType, target_phase: PhaseType
    ) -> HeuristicResult:
        """Increase the OID phase towards the target phase.

        Args
        ----
        oid : UUID
            The OID to increase phase for
        current_phase : PhaseType
            Current OID phase
        target_phase : PhaseType
            Target phase to reach

        Returns
        -------
        HeuristicResult
            HeuristicResult indicating success/failure
        """
        # Implementation would handle phase increase logic
        # For now, return success
        return self.success_result(
            f"Increased OID {oid} phase from {current_phase} towards {target_phase}"
        )


class DecreaseOidPhaseHeuristic(BaseHeuristic):
    """Heuristic to decrease the OID phase."""

    async def execute(
        self, oid: UUID, current_phase: PhaseType, target_phase: PhaseType
    ) -> HeuristicResult:
        """Decrease the OID phase towards the target phase.

        Args
        ----
        oid : UUID
            The OID to decrease phase for
        current_phase : PhaseType
            Current OID phase
        target_phase : PhaseType
            Target phase to reach

        Returns
        -------
        HeuristicResult
            HeuristicResult indicating success/failure
        """
        # Implementation would handle phase decrease logic
        # For now, return success
        return self.success_result(
            f"Decreased OID {oid} phase from {current_phase} towards {target_phase}"
        )


class DeleteUidHeuristic(BaseHeuristic):
    """Heuristic to safely delete a UID payload while preserving OID resilience."""

    def __init__(self, session: AsyncSession):
        super().__init__(session)
        self.combine_heuristic = CombineUidPhasesHeuristic(session)

    async def execute(self, uid: UUID) -> HeuristicResult:
        """Execute UID deletion heuristic according to deletion sequence diagram.

        Steps:
        1. Query UID entry and resolve OID
        2. Query other UID phases for OID
        3. Determine result phase if UID removed
        4. Reject if result phase < target phase
        5. Delete payload from storage
        6. Mark UID deleted + update OID phase

        Args
        ----
        uid : UUID
            The UID to delete

        Returns
        -------
        HeuristicResult
            HeuristicResult
        """
        try:
            # Step 1: Fetch target UID to get OID
            stmt = select(DataItem).where(DataItem.UID == uid)
            result = await self.session.execute(stmt)
            data_item = result.scalar()

            if not data_item:
                return HeuristicResult(False, f"No data found for UID {uid}")

            if not data_item.OID:
                return HeuristicResult(False, f"UID {uid} has no associated OID")

            oid = data_item.OID
            target_phase = data_item.target_phase

            # Step 2: Fetch other UIDs for same OID that are not already deleted
            uid_stmt = select(DataItem.UID_phase, DataItem.UID).where(
                DataItem.OID == oid,
                DataItem.deleted.is_(False),
            )
            uid_result = await self.session.execute(uid_stmt)
            remaining_rows = [r for r in uid_result.fetchall() if r[1] != uid]
            remaining_phases = [r[0] for r in remaining_rows]

            if remaining_phases:
                combine_result = await self.combine_heuristic.execute(remaining_phases)
                if not combine_result.success:
                    return combine_result
                # Step 2: Get resulting phase after deletion
                result_phase = combine_result.data["actual_phase"]
            else:
                # No remaining replicas; resilience phase reduces to GAS
                result_phase = PhaseType.GAS

            if PHASE_ORDER[result_phase] > PHASE_ORDER[target_phase]:
                # Here we could try to create another copy by
                # calling the IncreaseOidPhaseHeuristic, once implemented
                return HeuristicResult(
                    False,
                    "Deletion would violate resilience policy",
                    {
                        "oid": oid,
                        "uid": uid,
                        "result_phase": result_phase,
                        "target_phase": target_phase,
                    },
                )

            # Delete payload from storage manager
            if not dlm_storage_requests.delete_data_item_payload(str(uid)):
                return HeuristicResult(False, f"Failed to delete payload for UID {uid}")

            # Update UID metadata
            update_uid_stmt = (
                update(DataItem)
                .where(DataItem.UID == uid)
                .values(
                    item_state=ItemState.DELETED,
                    deleted=True,
                    UID_deletion=func.now(),  # pylint: disable=not-callable
                )
            )
            await self.session.execute(update_uid_stmt)

            # Update OID phase for the OID group
            update_oid_stmt = (
                update(DataItem).where(DataItem.OID == oid).values(OID_phase=result_phase)
            )
            await self.session.execute(update_oid_stmt)

            await self.session.commit()

            return self.success_result(
                f"Deleted UID {uid} payload and updated OID {oid} phase to {result_phase}",
                {"uid": uid, "oid": oid, "result_phase": result_phase},
            )

        except Exception as exc:
            # Any other exception: roll back
            await self.session.rollback()
            return HeuristicResult(False, f"Error executing UID deletion heuristic: {str(exc)}")


class UidExpiryHeuristic(BaseHeuristic):
    """Heuristic to discover expired UIDs and delegate deletion."""

    def __init__(self, session: AsyncSession):
        super().__init__(session)
        self.delete_heuristic = DeleteUidHeuristic(session)

    async def execute(self) -> HeuristicResult:
        """Execute the UID expiry heuristic.

        The heuristic discovers any UIDs whose expiration timestamp has passed,
        then delegates their cleanup to the delete heuristic.

        Returns
        -------
        HeuristicResult
            The result of the expiry scan and delegated deletions.
        """
        try:
            stmt = select(DataItem.UID).where(
                DataItem.UID_expiration < func.now(),  # pylint: disable=not-callable
                DataItem.deleted.is_(False),
            )
            result = await self.session.execute(stmt)
            expired_rows = result.fetchall()
            expired_uids = [row[0] for row in expired_rows]

            if not expired_uids:
                return self.success_result("No expired UIDs found", {"expired_uids": []})

            deletion_results = []
            for uid in expired_uids:
                delete_result = await self.delete_heuristic.execute(uid)
                deletion_results.append(
                    {
                        "uid": uid,
                        "success": delete_result.success,
                        "message": delete_result.message,
                    }
                )

            success = all(item["success"] for item in deletion_results)
            message = "Deleted expired UIDs" if success else "Some expired UID deletions failed"

            return HeuristicResult(
                success,
                message,
                {"expired_uids": expired_uids, "deletion_results": deletion_results},
            )

        except Exception as exc:
            await self.session.rollback()
            return HeuristicResult(False, f"Error executing UID expiry heuristic: {str(exc)}")


class OidExpiryHeuristic(BaseHeuristic):
    """Heuristic to discover expired OIDs and delete their UIDs."""

    def __init__(self, session: AsyncSession):
        super().__init__(session)
        self.delete_heuristic = DeleteUidHeuristic(session)

    async def execute(self) -> HeuristicResult:
        """Execute the OID expiry heuristic.

        The heuristic discovers any expired OIDs and delegates deletion of their
        associated UIDs to the delete heuristic.

        Returns
        -------
        HeuristicResult
            The result of the OID expiry scan and delegated UID deletions.
        """
        try:
            stmt = (
                select(DataItem.OID)
                .distinct()
                .where(
                    DataItem.OID_expiration < func.now(),  # pylint: disable=not-callable
                    DataItem.deleted.is_(False),
                    DataItem.OID.is_not(None),
                )
            )
            result = await self.session.execute(stmt)
            expired_rows = result.fetchall()
            expired_oids = [row[0] for row in expired_rows]

            if not expired_oids:
                return self.success_result("No expired OIDs found", {"expired_oids": []})

            deletion_results = []
            for oid in expired_oids:
                uid_stmt = select(DataItem.UID).where(
                    DataItem.OID == oid,
                    DataItem.deleted.is_(False),
                )
                uid_result = await self.session.execute(uid_stmt)
                uid_rows = uid_result.fetchall()
                for uid_row in uid_rows:
                    uid = uid_row[0]
                    delete_result = await self.delete_heuristic.execute(uid)
                    deletion_results.append(
                        {
                            "oid": oid,
                            "uid": uid,
                            "success": delete_result.success,
                            "message": delete_result.message,
                        }
                    )

            success = all(item["success"] for item in deletion_results)
            message = "Deleted expired OIDs" if success else "Some expired OID deletions failed"

            return HeuristicResult(
                success,
                message,
                {"expired_oids": expired_oids, "deletion_results": deletion_results},
            )

        except Exception as exc:
            await self.session.rollback()
            return HeuristicResult(False, f"Error executing OID expiry heuristic: {str(exc)}")


class OidPhaseEnforceHeuristic(BaseHeuristic):
    """Heuristic to enforce OID phase consistency with UID phases and target phase."""

    def __init__(self, session: AsyncSession):
        super().__init__(session)
        self.combine_heuristic = CombineUidPhasesHeuristic(session)
        self.increase_heuristic = IncreaseOidPhaseHeuristic(session)
        self.decrease_heuristic = DecreaseOidPhaseHeuristic(session)

    async def execute(self, oid: UUID) -> HeuristicResult:
        """Execute the OID Phase Enforce heuristic.

        This heuristic:
        1. Queries the database for OID phase, UID phases, and target phase
        2. Combines UID phases to get actual phase
        3. Compares phases and takes appropriate action:
        - If target_phase == actual_phase and OID_phase != actual_phase: update OID_phase
        - If target_phase < actual_phase: call increase heuristic
        - If target_phase > actual_phase: call decrease heuristic

        Args
        ----
        oid : UUID
            The OID to enforce phase consistency for

        Returns
        -------
        HeuristicResult
            The result of the heuristic execution
        """
        try:
            # Query OID and UID phases
            stmt = select(DataItem).where(DataItem.OID == oid)

            result = await self.session.execute(stmt)
            data_item = result.scalar()

            if not data_item:
                return HeuristicResult(False, f"No data found for OID {oid}")

            oid_phase = data_item.OID_phase
            target_phase = data_item.target_phase

            # Query all UID phases for this OID
            uid_stmt = select(DataItem.UID_phase).where(DataItem.OID == oid)
            uid_result = await self.session.execute(uid_stmt)
            uid_phases = [row[0] for row in uid_result.fetchall()]

            # Combine UID phases
            combine_result = await self.combine_heuristic.execute(uid_phases)
            if not combine_result.success:
                return combine_result

            actual_phase = combine_result.data["actual_phase"]

            # Decision logic
            if target_phase == actual_phase and oid_phase != actual_phase:
                # Update OID phase to match actual phase
                # Query all data items with this OID and update their OID_phase
                update_stmt = (
                    update(DataItem).where(DataItem.OID == oid).values(OID_phase=actual_phase)
                )
                await self.session.execute(update_stmt)
                await self.session.commit()
                return self.success_result(f"Updated OID {oid} phase to {actual_phase}")

            if PHASE_ORDER.get(target_phase, float("inf")) > PHASE_ORDER.get(
                actual_phase, float("inf")
            ):
                # Target phase has lower resilience than actual phase - need to increase
                increase_result = await self.increase_heuristic.execute(
                    oid, oid_phase, target_phase
                )
                return increase_result

            if PHASE_ORDER.get(target_phase, float("inf")) < PHASE_ORDER.get(
                actual_phase, float("inf")
            ):
                # Target phase has higher resilience than actual phase - need to decrease
                decrease_result = await self.decrease_heuristic.execute(
                    oid, oid_phase, target_phase
                )
                return decrease_result

            # Phases are consistent
            return self.success_result(f"OID {oid} phases are consistent")

        except Exception as e:
            await self.session.rollback()
            return HeuristicResult(False, f"Error executing OID Phase Enforce heuristic: {str(e)}")
