"""Heuristic implementations for DLM data lifecycle management.
NOTE: Generated by copilot from OID_phase_enforce sequence diagram.

PROMPT: Use this sequence diagram to create python code with a abstract 
class for heuristics and the OID Phase heuristics as one implementation.
"""

from abc import ABC, abstractmethod
from typing import List, Optional
from uuid import UUID

from sqlalchemy.ext.asyncio import AsyncSession

from ska_dlm.dlm_db.db_access import DB

from ska_dlm.common_types import PhaseType


class HeuristicResult:
    """Result of a heuristic execution."""

    def __init__(self, success: bool, message: str = "", data: Optional[dict] = None):
        self.success = success
        self.message = message
        self.data = data or {}


class BaseHeuristic(ABC):
    """Abstract base class for all heuristics."""

    def __init__(self, session: AsyncSession):
        self.session = session

    @abstractmethod
    async def execute(self, **kwargs) -> HeuristicResult:
        """Execute the heuristic logic.

        Args:
            **kwargs: Heuristic-specific parameters

        Returns:
            HeuristicResult: The result of the heuristic execution
        """
        pass

    @classmethod
    def success_result(cls, message: str = "", data: Optional[dict] = None) -> HeuristicResult:
        """Create a successful heuristic result.

        Args:
            message: Optional success message
            data: Optional data dictionary

        Returns:
            HeuristicResult with success=True
        """
        return HeuristicResult(True, message, data)


class CombineUidPhasesHeuristic(BaseHeuristic):
    """Heuristic to combine UID phases into a single actual phase."""

    async def execute(self, oid: UUID, uid_phases: List[PhaseType]) -> HeuristicResult:
        """Combine UID phases to determine the actual phase for an OID.

        The logic here is to take the highest phase among all UIDs.
        Phase hierarchy: GAS < LIQUID < SOLID < PLASMA

        Args:
            oid: The OID to combine phases for
            uid_phases: List of UID phases

        Returns:
            HeuristicResult with the combined actual phase
        """
        if not uid_phases:
            return HeuristicResult(False, "No UID phases provided")

        # Phase hierarchy for comparison
        phase_order = {PhaseType.GAS: 0, PhaseType.LIQUID: 1, PhaseType.SOLID: 2, PhaseType.PLASMA: 3}

        # Find the highest phase
        actual_phase = max(uid_phases, key=lambda p: phase_order[p])

        return self.success_result(f"Combined phase: {actual_phase}", {"actual_phase": actual_phase})


class IncreaseOidPhaseHeuristic(BaseHeuristic):
    """Heuristic to increase the OID phase."""

    async def execute(self, oid: UUID, current_phase: PhaseType, target_phase: PhaseType) -> HeuristicResult:
        """Increase the OID phase towards the target phase.

        Args:
            oid: The OID to increase phase for
            current_phase: Current OID phase
            target_phase: Target phase to reach

        Returns:
            HeuristicResult indicating success/failure
        """
        # Implementation would handle phase increase logic
        # For now, return success
        return self.success_result(f"Increased OID {oid} phase from {current_phase} towards {target_phase}")


class DecreaseOidPhaseHeuristic(BaseHeuristic):
    """Heuristic to decrease the OID phase."""

    async def execute(self, oid: UUID, current_phase: PhaseType, target_phase: PhaseType) -> HeuristicResult:
        """Decrease the OID phase towards the target phase.

        Args:
            oid: The OID to decrease phase for
            current_phase: Current OID phase
            target_phase: Target phase to reach

        Returns:
            HeuristicResult indicating success/failure
        """
        # Implementation would handle phase decrease logic
        # For now, return success
        return self.success_result(f"Decreased OID {oid} phase from {current_phase} towards {target_phase}")


class OidPhaseEnforceHeuristic(BaseHeuristic):
    """Heuristic to enforce OID phase consistency with UID phases and target phase."""

    def __init__(self, session: AsyncSession):
        super().__init__(session)
        self.combine_heuristic = CombineUidPhasesHeuristic(session)
        self.increase_heuristic = IncreaseOidPhaseHeuristic(session)
        self.decrease_heuristic = DecreaseOidPhaseHeuristic(session)

    async def execute(self, oid: UUID) -> HeuristicResult:
        """Execute the OID Phase Enforce heuristic.

        This heuristic:
        1. Queries the database for OID phase, UID phases, and target phase
        2. Combines UID phases to get actual phase
        3. Compares phases and takes appropriate action:
           - If target_phase == actual_phase and OID_phase != actual_phase: update OID_phase
           - If target_phase < actual_phase: call increase heuristic
           - If target_phase > actual_phase: call decrease heuristic

        Args:
            oid: The OID to enforce phase consistency for

        Returns:
            HeuristicResult: The result of the heuristic execution
        """
        from sqlalchemy import select, update
        from ska_dlm.dlm_db.models import DataItem

        try:
            # Query OID and UID phases
            stmt = select(DataItem).where(DataItem.OID == oid)

            result = await self.session.execute(stmt)
            data_item = result.scalar()

            if not data_item:
                return HeuristicResult(False, f"No data found for OID {oid}")

            oid_phase = data_item.OID_phase
            target_phase = data_item.target_phase

            # Query all UID phases for this OID
            uid_stmt = select(DataItem.UID_phase).where(DataItem.OID == oid)
            uid_result = await self.session.execute(uid_stmt)
            uid_phases = [row[0] for row in uid_result.fetchall()]

            # Combine UID phases
            combine_result = await self.combine_heuristic.execute(oid, uid_phases)
            if not combine_result.success:
                return combine_result

            actual_phase = combine_result.data["actual_phase"]

            # Phase hierarchy for comparison
            phase_order = {PhaseType.GAS: 0, PhaseType.LIQUID: 1, PhaseType.SOLID: 2, PhaseType.PLASMA: 3}

            # Decision logic
            if target_phase == actual_phase and oid_phase != actual_phase:
                # Update OID phase to match actual phase
                # Query all data items with this OID and update their OID_phase
                update_stmt = (
                    update(DataItem)
                    .where(DataItem.OID == oid)
                    .values(OID_phase = actual_phase)
                )
                await self.session.execute(update_stmt)
                await self.session.commit()
                return self.success_result(f"Updated OID {oid} phase to {actual_phase}")

            elif phase_order.get(target_phase, 0) < phase_order.get(actual_phase, 0):
                # Target phase is lower than actual phase - need to increase
                increase_result = await self.increase_heuristic.execute(oid, oid_phase, target_phase)
                return increase_result

            elif phase_order.get(target_phase, 0) > phase_order.get(actual_phase, 0):
                # Target phase is higher than actual phase - need to decrease
                decrease_result = await self.decrease_heuristic.execute(oid, oid_phase, target_phase)
                return decrease_result

            else:
                # Phases are consistent
                return self.success_result(f"OID {oid} phases are consistent")

        except Exception as e:
            await self.session.rollback()
            return HeuristicResult(False, f"Error executing OID Phase Enforce heuristic: {str(e)}")