FROM library/postgres:17.5
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y vim \
    postgresql-contrib \
    postgresql-17-q3c \
    postgresql-17-pgsphere
RUN echo "en_US.UTF-8 UTF-8"> /etc/locale.gen && locale-gen
