FROM python:3.10

RUN apt-get update && apt-get install -y rclone iputils-ping
RUN pip install pytest requests_mock kubernetes docker

ARG POETRY_VERSION=1.8.2
RUN pip install poetry==${POETRY_VERSION}

RUN mkdir -p /data

WORKDIR /app

# cache external dependencies
COPY pyproject.toml poetry.lock ./
RUN poetry config virtualenvs.in-project true \
    && poetry install --only main,test --no-root

COPY ./ ./
RUN poetry install --only main,test

ARG DO_AUTH
ENV DO_AUTH=${DO_AUTH}

ENV PATH="/app/.venv/bin:${PATH}"

CMD pytest --env docker --auth ${DO_AUTH}
