FROM python:3.10

RUN apt-get update && apt-get install -y
RUN pip install "fastapi[standard]" python-keycloak pyjwt[crypto] msal itsdangerous overrides


WORKDIR /app
RUN openssl req -x509 -newkey rsa:4096 -keyout ./key.pem -out ./cert.pem -sha256 -days 3650 -nodes -subj "/C=XX/ST=StateName/L=CityName/O=CompanyName/OU=CompanySectionName/CN=CommonNameOrHostname"
COPY ./tests/integration/gateway/dlm_gateway.py ./tests/integration/gateway/dlm_gateway.py

ARG PORT
ENV PORT=${PORT}

CMD fastapi dev /app/tests/integration/gateway/dlm_gateway.py --port ${PORT} --host 0.0.0.0
