FROM rclone/rclone

RUN apk update && \
    apk add --no-cache openssl openssh-client openssh-keygen
RUN openssl req -x509 -nodes -days 365 \
    -subj "/C=CA/ST=QC/O=SKAO, Inc./CN=skao.int" \
    -addext "subjectAltName=DNS:skao.int" \
    -newkey rsa:2048 \
    -keyout /etc/ssl/private/selfsigned.key \
    -out /etc/ssl/certs/selfsigned.cert
