FROM python:3.10

RUN apt-get update && apt-get install -y 
RUN pip install "fastapi[standard]" python-keycloak

WORKDIR /app
COPY ./tests/integration/gateway/dlm_gateway.py ./tests/integration/gateway/dlm_gateway.py

ARG PORT
ENV PORT=${PORT}

CMD fastapi dev /app/tests/integration/gateway/dlm_gateway.py --port ${PORT} --host 0.0.0.0