FROM python:3.10

RUN apt-get update && apt-get install -y python3-casacore rclone iputils-ping
RUN pip install pytest requests_mock kubernetes docker

ARG POETRY_VERSION=1.8.2
RUN pip install poetry==${POETRY_VERSION}

RUN mkdir -p /data

WORKDIR /app

COPY pyproject.toml poetry.lock ./
RUN poetry config virtualenvs.in-project true \
    && poetry install --no-root

COPY ./ ./
RUN poetry install

ARG DO_AUTH
ENV DO_AUTH=${DO_AUTH}

ENV PATH="/app/.venv/bin:${PATH}"

COPY ./tests/volumes/config-dockercompose.yaml /root/.dlm/config.yaml
ENTRYPOINT pytest --env docker --auth ${DO_AUTH}
