FROM python:3.10

RUN apt-get update && apt-get install -y python3-casacore rclone iputils-ping
RUN pip install pytest requests_mock kubernetes docker

ARG POETRY_VERSION=1.8.2
RUN pip install poetry==${POETRY_VERSION}

RUN mkdir -p /data

WORKDIR /app

COPY pyproject.toml poetry.lock ./
RUN poetry export --output=requirements.txt --without-hashes && \
    pip install --extra-index-url https://artefact.skao.int/repository/pypi-internal/simple -r requirements.txt

COPY ./ ./
RUN pip install .

ENTRYPOINT pytest --env docker
