global:
  dataProduct:
    api:
      url: http://ska-dataproduct-dashboard-api-service.ci-dev-ska-dataproduct-dashboard.svc:8000

gateway:
  enabled: true

postgresql:
  enabled: true
  initialise: true

keycloak:
  enabled: true

pgweb:
  enabled: true