global:
  storageClass: nfss1
  ingress:
    enabled: true
  dataProductVolume:
    name: shared
    pvc:
      name: shared

gateway:
  enabled: true

postgresql:
  enabled: true
  initialise: true

keycloak:
  enabled: false

pgweb:
  enabled: true