apiVersion: v1
kind: PersistentVolume
metadata:
  name: foo-pv
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  claimRef:
    name: test-pvc
    namespace: dlm-testing
  hostPath:
    path: "/tmp"
