# Default values for the SKA Data Lifecycle Management system.
# This is a YAML-formatted file.

REST:
  base_url: "http://localhost:3001"

DLM:
  dlm_db: "ska_dlm_meta"
  dlm_table: "data_item"
  storage_table: "storage"
  storage_config_table: "storage_config"
  location_table: "location"
  STORAGE_WARNING_PERCENTAGE: 80.0
  SLEEP_DURATION: 10 # seconds

RCLONE:
  url: "http://localhost:5572"
