# Default values for the SKA Data Lifecycle Management system.
# This is a YAML-formatted file.

DLM:
  dlm_db: "ska_dlm_meta"
  dlm_table: "data_item"
  storage_table: "storage"
  storage_config_table: "storage_config"
  location_table: "location"
  migration_table: "migration"
  storage_manager:
    storage_warning_percentage: 80.0
    polling_interval: 10 # seconds
  migration_manager:
    polling_interval: 10 # seconds

REST:
  base_url: "http://localhost:3000"

RCLONE:
  - "https://localhost:5572"
