# Default values for the SKA Data Lifecycle Management system.
# This is a YAML-formatted file.

DB:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "!db_password"

REST:
  base_url: "http://localhost:3001"
  cfg_file: "{DLM_PATH}/postgREST.conf"

DLM:
  dlm_db: "ska_dlm_meta"
  dlm_table: "data_item"
  storage_table: "storage"
  location_table: "location"
