# Default values for the SKA Data Lifecycle Management system.
# This is a YAML-formatted file.

REST:
  base_url: "http://localhost:3001"

DLM:
  dlm_db: "ska_dlm_meta"
  dlm_table: "data_item"
  storage_table: "storage"
  storage_config_table: "storage_config"
  location_table: "location"
  storage_manager:
    storage_warning_percentage: 80.0
    polling_interval: 10 # seconds

RCLONE:
  url: "http://localhost:5572"

DATA_PRODUCT_API:
  url: "http://localhost:8000"
