# https://helm.sh/docs/developing_charts/
apiVersion: v2
name: ska-dlm
version: 1.2.0
appVersion: 1.2.0
description: SKA Data Lifecycle Manager
home: https://developer.skao.int/projects/
sources:
- https://gitlab.com/ska-telescope/ska-data-lifecycle
maintainers:
- name: Mark Boulton
  email: mark.boulton@icrar.org
- name: Callan Gray
  email: callan.gray@icrar.org
- name: Andreas Wicenec
  email: andreas.wicenec@icrar.org
- name: Rodrigo Tobar
  email: rtobar@icrar.org
dependencies:
- name: postgresql
  version: 16.7.27
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
- name: pgweb
  version: 0.1.9
  repository: https://charts.ectobit.com
  condition: pgweb.enabled
