{{- if $.Values.keycloak.enabled }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ska-dlm.fullname" . }}-keycloak-realm-configmap
  namespace: {{ .Release.Namespace }}
data:
{{ (.Files.Glob "keycloak/realm-export.json").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ska-dlm.fullname" . }}-keycloak-gateway-configmap
  namespace: {{ .Release.Namespace }}
data:
  PROVIDER: KC
  AUTH: "1"
  {{- if $.Values.keycloak.use_https }}
  KEYCLOAK_URL: "https://{{ include "ska-dlm.fullname" . }}-keycloak.{{ .Release.Namespace }}.svc.cluster.local"
  {{- else }}
  KEYCLOAK_URL: "http://{{ include "ska-dlm.fullname" . }}-keycloak.{{ .Release.Namespace }}.svc.cluster.local"
  {{- end }}
{{- else }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ska-dlm.fullname" . }}-entra-gateway-configmap
  namespace: {{ .Release.Namespace }}
data:
  PROVIDER: ENTRA
  AUTH: "1"
{{- end }}
