{{- if $.Values.keycloak.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ska-dlm.fullname" . }}-keycloak-gateway-secret
  namespace: {{ .Release.Namespace }}
stringData:
  REALM: "test"
  CLIENT_ID: "dlm"
  CLIENT_SECRET: "xU2a9SOTLJZSwvAzAlfoucqg4sCMgY6O"
  STATE: "magic_string"
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ska-dlm.fullname" . }}-entra-gateway-secret
  namespace: {{ .Release.Namespace }}
stringData:
  TENANT_ID: ref+vault://kv/users/calgray/sdhp-stfc/ska-dlm/integration?address=https://vault.skao.int#/TENANT_ID
  CLIENT_ID: ref+vault://kv/users/calgray/sdhp-stfc/ska-dlm/integration?address=https://vault.skao.int#/CLIENT_ID
  CLIENT_CRED: ref+vault://kv/users/calgray/sdhp-stfc/ska-dlm/integration?address=https://vault.skao.int#/CLIENT_CRED
  COOKIE_SECRET: ref+vault://kv/users/calgray/sdhp-stfc/ska-dlm/integration?address=https://vault.skao.int#/COOKIE_SECRET
{{- end }}
