apiVersion: v1
kind: ConfigMap
metadata:
  name: ska-dlm-db-migrations-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ska-dlm.postgrest.labels" . | nindent 4 }}
data:
  changelog.yaml: |-
{{ .Files.Get "changelog.yaml" | indent 4 }}
{{ (.Files.Glob "initdb-scripts/*.sql").AsConfig | indent 2 }}
{{ (.Files.Glob "patches/**/*.sql").AsConfig | indent 2 }}
