{{- if not .Values.postgresql.enabled }}
{{- if .Values.database.migration.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "ska-dlm.fullname" . }}-db-migration
spec:
  template:
    spec:
      containers:
      - name: {{ include "ska-dlm.fullname" . }}-db-migration
        image: {{ .Values.database.migration.image }}:{{ .Values.database.migration.version }}
        command: ["/bin/sh", "-c"]
        args:
        - >
          psql -f /etc/sql/10_create_tables.sql &&
          psql -f /etc/sql/20_alter_data_item_metadata_to_jsonb.sql
        env:
        {{ range $envvar_name := tuple "PGUSER" "PGPASSWORD" "PGHOST" "PGDATABASE" -}}
        - name: {{ $envvar_name }}
          valueFrom:
            secretKeyRef:
              name: {{ include "ska-dlm.postgrest.db-auth-secret-name" $ }}
              key: {{ $envvar_name }}
              optional: false
        {{ end -}}
        - name: PGPORT
          valueFrom:
            secretKeyRef:
              name: {{ include "ska-dlm.postgrest.db-auth-secret-name" $ }}
              key: PGPORT
              optional: true
        volumeMounts:
        - name: sql-volume
          mountPath: "/etc/sql/"
      volumes:
      - name: sql-volume
        configMap:
          name: ska-dlm-postgresql-initdb-scripts
      restartPolicy: Never
  backoffLimit: 4
  {{- end }}
  {{- end }}