apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ska-dlm.fullname" . }}-configmap
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |-
    DLM:
      dlm_db: "ska_dlm_meta"
      dlm_table: "data_item"
      storage_table: "storage"
      storage_config_table: "storage_config"
      location_table: "location"
      storage_manager:
        storage_warning_percentage: 80.0
        polling_interval: 10 # seconds
    REST:
      base_url: "http://{{ include "ska-dlm.fullname" . }}-postgrest.{{ .Release.Namespace }}.svc.cluster.local"
    RCLONE:
      url: "http://{{ include "ska-dlm.fullname" . }}-rclone.{{ .Release.Namespace }}.svc.cluster.local"
