{{- if and (.Values.gateway.enabled) (ne .Values.gateway.secret.name "") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ska-dlm.fullname" . }}-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ska-dlm.gateway.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http-port
      protocol: TCP
  selector:
    component: {{ .Values.gateway.component }}
    subsystem: {{ .Values.gateway.subsystem }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ska-dlm.fullname" . }}-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ska-dlm.gateway.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.gateway.replicas }}
  selector:
    matchLabels:
      component: {{ .Values.gateway.component }}
      subsystem: {{ .Values.gateway.subsystem }}
  template:
    metadata:
      labels:
        {{- include "ska-dlm.gateway.labels" . | indent 8 }}
    spec:
      containers:
      - name: gateway
        image: {{ .Values.gateway.image }}:{{ .Values.gateway.version }}
        imagePullPolicy: {{ .Values.gateway.imagePullPolicy }}
        command:
        - /bin/bash
        - -ec
        args:
          - >-
            fastapi {{ ternary "dev" "run" .Values.global.development }}
            /app/tests/integration/gateway/dlm_gateway.py
            --host 0.0.0.0 --port 8000
        ports:
        - containerPort: 8000
          name: http-port
        readinessProbe:
          httpGet:
            path: /heartbeat
            port: http-port
          periodSeconds: 5
          initialDelaySeconds: 5
        livenessProbe:
          httpGet:
            path: /heartbeat
            port: http-port
          periodSeconds: 5
          initialDelaySeconds: 5
        env:
        - name: PORT
          value: "8000"
        - name: REDIRECT_URL
        {{- if $.Values.global.ingress.enabled }}
          value: "https://{{ .Values.global.ingress.domainName }}/{{ .Release.Namespace }}/dlm/auth_callback"
        {{- else }}
          value: "http://{{ include "ska-dlm.fullname" . }}-gateway.{{ .Release.Namespace }}/auth_callback"
        {{- end }}
        - name: INGEST_CLIENT
          value: "http://{{ include "ska-dlm.fullname" . }}-ingest.{{ .Release.Namespace }}:80"
        - name: REQUESTS_CLIENT
          value: "http://{{ include "ska-dlm.fullname" . }}-request.{{ .Release.Namespace }}:80"
        - name: STORAGE_CLIENT
          value: "http://{{ include "ska-dlm.fullname" . }}-storage.{{ .Release.Namespace }}:80"
        - name: MIGRATION_CLIENT
          value: "http://{{ include "ska-dlm.fullname" . }}-migration.{{ .Release.Namespace }}:80"
        {{ range $envvar_name := tuple "PROVIDER" "TENANT_ID" "CLIENT_ID" "CLIENT_CRED" -}}
        - name: {{ $envvar_name }}
          valueFrom:
            secretKeyRef:
              name: {{ include "ska-dlm.gateway.secret.name" $ }}
              key: {{ $envvar_name }}
              optional: false
        {{ end -}}
        envFrom:
        - configMapRef:
            name: "{{ include "ska-dlm.fullname" . }}-sqlalchemy-configmap"
        - secretRef:
            name: "{{ include "ska-dlm.fullname" . }}-sqlalchemy-secret"
        {{- if $.Values.keycloak.enabled }}
        - configMapRef:
            name: "{{ include "ska-dlm.fullname" . }}-keycloak-gateway-configmap"
        - secretRef:
            name: "{{ include "ska-dlm.fullname" . }}-keycloak-gateway-secret"
        {{- end }}
{{- end }}
