{{- if $.Values.gateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ska-dlm.fullname" . }}-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ska-dlm.gateway.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    component: {{ .Values.gateway.component }}
    subsystem: {{ .Values.gateway.subsystem }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ska-dlm.fullname" . }}-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ska-dlm.gateway.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.gateway.replicas }}
  selector:
    matchLabels:
      component: {{ .Values.gateway.component }}
      subsystem: {{ .Values.gateway.subsystem }}
  template:
    metadata:
      labels:
        {{- include "ska-dlm.gateway.labels" . | indent 8 }}
      {{- if and (eq $.Values.keycloak.enabled false) (eq $.Values.gateway.vault.enabled true) }}
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-status: "update"
        vault.hashicorp.com/role: "kube-role"
        vault.hashicorp.com/agent-inject-secret-config: "{{ .Values.gateway.vault.path }}"
        vault.hashicorp.com/agent-inject-template-config: |-
          {{`{{ with secret `}}"{{ .Values.gateway.vault.path }}"{{` }}
            {{ range $k, $v := .Data.data }}
              export {{ $k }}={{ $v }}
            {{ end }}
          {{ end }}`}}
      {{- end }}
    spec:
      containers:
      - name: gateway
        image: {{ .Values.gateway.image }}:{{ .Values.gateway.version }}
        imagePullPolicy: {{ .Values.gateway.imagePullPolicy }}
        command:
        - /bin/bash
        - -ec
        args:
          {{- if and (eq $.Values.keycloak.enabled false) (eq $.Values.gateway.vault.enabled true) }}
          - >-
            . /vault/secrets/config &&
            fastapi {{ ternary "dev" "run" .Values.global.development }}
            /app/tests/integration/gateway/dlm_gateway.py
            --host 0.0.0.0 --port 8000
          {{- else }}
          - >-
            fastapi {{ ternary "dev" "run" .Values.global.development }}
            /app/tests/integration/gateway/dlm_gateway.py
            --host 0.0.0.0 --port 8000
          {{- end }}
        readinessProbe:
          httpGet:
            path: /heartbeat
            port: 8000
          periodSeconds: 5
          initialDelaySeconds: 5
        livenessProbe:
          httpGet:
            path: /heartbeat
            port: 8000
          periodSeconds: 5
          initialDelaySeconds: 5
        env:
        - name: PORT
          value: "8000"
        - name: REDIRECT_URL
        {{- if $.Values.global.ingress.enabled }}
          value: "https://{{ .Values.global.ingress.domainName }}/{{ .Release.Namespace }}/dlm/auth_callback"
        {{- else }}
          value: "http://{{ include "ska-dlm.fullname" . }}-gateway.{{ .Release.Namespace }}.svc.cluster.local/auth_callback"
        {{- end }}
        - name: INGEST_CLIENT
          value: "http://{{ include "ska-dlm.fullname" . }}-ingest.{{ .Release.Namespace }}.svc.cluster.local:80"
        - name: REQUESTS_CLIENT
          value: "http://{{ include "ska-dlm.fullname" . }}-request.{{ .Release.Namespace }}.svc.cluster.local:80"
        - name: STORAGE_CLIENT
          value: "http://{{ include "ska-dlm.fullname" . }}-storage.{{ .Release.Namespace }}.svc.cluster.local:80"
        - name: MIGRATION_CLIENT
          value: "http://{{ include "ska-dlm.fullname" . }}-migration.{{ .Release.Namespace }}.svc.cluster.local:80"
        envFrom:
        {{- if $.Values.keycloak.enabled }}
        - configMapRef:
            name: "{{ include "ska-dlm.fullname" . }}-keycloak-gateway-configmap"
        - secretRef:
            name: "{{ include "ska-dlm.fullname" . }}-keycloak-gateway-secret"
        {{- else }}
        - configMapRef:
            name: "{{ include "ska-dlm.fullname" . }}-entra-gateway-configmap"
        - secretRef:
            name: "{{ include "ska-dlm.fullname" . }}-entra-gateway-secret"
        {{- end }}
{{- end }}