apiVersion: v1
kind: Service
metadata:
  name: {{ include "ska-dlm.fullname" . }}-heuristic
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ska-dlm.heuristic.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    component: {{ .Values.heuristic.component }}
    subsystem: {{ .Values.heuristic.subsystem }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ska-dlm.fullname" . }}-heuristic
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ska-dlm.heuristic.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.heuristic.replicas }}
  selector:
    matchLabels:
      component: {{ .Values.heuristic.component }}
      subsystem: {{ .Values.heuristic.subsystem }}
  template:
    metadata:
      labels:
        {{- include "ska-dlm.heuristic.labels" . | nindent 8 }}
    spec:
      initContainers:
      - name: wait-for-postgres
        image: postgres:17.4
        command: ['sh', '-c', 'until pg_isready -h "$PGHOST" -p "$PGPORT" -U "$PGUSER" -d "$PGDATABASE"; do echo waiting for database; sleep 2; done;']
        env:
        {{- range $envvar_name := tuple "PGUSER" "PGPASSWORD" "PGHOST" "PGDATABASE" }}
        - name: {{ $envvar_name }}
          valueFrom:
            secretKeyRef:
              name: {{ include "ska-dlm.postgrest.db-auth-secret-name" $ }}
              key: {{ $envvar_name }}
        {{- end }}
        - name: PGPORT
          valueFrom:
            secretKeyRef:
              name: {{ include "ska-dlm.postgrest.db-auth-secret-name" $ }}
              key: PGPORT
              optional: true
      containers:
      - name: heuristic
        image: {{ .Values.heuristic.image}}:{{ .Values.heuristic.version }}
        imagePullPolicy: {{ .Values.heuristic.imagePullPolicy }}
        command:
        - ska-dlm-heuristic-engine
        env:
        {{- range $envvar_name := tuple "PGUSER" "PGPASSWORD" "PGHOST" "PGDATABASE" }}
        - name: {{ $envvar_name }}
          valueFrom:
            secretKeyRef:
              name: {{ include "ska-dlm.postgrest.db-auth-secret-name" $ }}
              key: {{ $envvar_name }}
        {{- end }}
        - name: PGPORT
          valueFrom:
            secretKeyRef:
              name: {{ include "ska-dlm.postgrest.db-auth-secret-name" $ }}
              key: PGPORT
              optional: true
        - name: DATABASE_URL
          value: "postgresql+asyncpg://$(PGUSER):$(PGPASSWORD)@$(PGHOST)/$(PGDATABASE)"
        - name: DLM_HEURISTIC_POLL_INTERVAL
          value: {{ .Values.heuristic.pollInterval | default 10 | quote}}
        volumeMounts:
        - name: dlm-configmap
          mountPath: "/home/ska-dlm/.dlm"
          readOnly: true
      volumes:
      - name: dlm-configmap
        configMap:
          name: {{ include "ska-dlm.fullname" . }}-configmap