{{ if .Values.global.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ska-dlm.name" . }}-gateway-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
        - path: /{{ .Release.Namespace }}/dlm(/|$)(.*)
          pathType: ImplementationSpecific
          backend:
           service:
            name: {{ include "ska-dlm.name" . }}-gateway
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ska-dlm.name" . }}-postgrest-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
        - path: /{{ .Release.Namespace }}/postgrest(/|$)(.*)
          pathType: ImplementationSpecific
          backend:
           service:
            name: {{ include "ska-dlm.name" . }}-postgrest
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ska-dlm.name" . }}-rclone-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
        - path: /{{ .Release.Namespace }}/rclone(/|$)(.*)
          pathType: ImplementationSpecific
          backend:
           service:
            name: {{ include "ska-dlm.name" . }}-rclone
            port:
              number: 80
{{ end }}