apiVersion: v1
kind: ConfigMap
metadata:
  name: ska-dlm-postgresql-initdb-scripts
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ska-dlm.postgrest.labels" . | indent 4 }}
data:
{{- if .Values.database.migration.enabled }}
  {{- if .Values.database.migration.base.baseInstall }}
    {{ (.Files.Glob "initdb-scripts/*.sql").AsConfig | indent 4 }}
  {{- end }}
{{- end }}