{{/* vim: set filetype=mustache: */}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: ska-dlm-postgresql-initdb-scripts
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ska-dlm.postgrest.labels" . | indent 4 }}
data:
{{- if .Values.database.migrate }}
{{ (.Files.Glob "initdb-scripts/*.sql").AsConfig | indent 2 }}
{{- end }}