apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ska-dlm.name" . }}-keycloak-realm-configmap
  namespace: {{ .Release.Namespace }}
data:
{{ (.Files.Glob "keycloak/realm-export.json").AsConfig | indent 2 }}
