{{- if .Values.postgresql.enabled }}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "ska-dlm.postgresql.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgresql

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "ska-dlm.postgresql.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: {{ include "ska-dlm.postgresql.name" . }}
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgres
          image: postgres:17-bookworm
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.auth.username | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresql.auth.password | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.auth.database | quote }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: initdb
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: data
          emptyDir: {}
        - name: initdb
          configMap:
            name: ska-dlm-postgresql-initdb-{{ .Release.Name }}


{{- end }}