apiVersion: v1
kind: Service
metadata:
  name: {{ include "ska-dlm.fullname" . }}-rclone
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ska-dlm.rclone.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: tcp-rclone
      port: 80
      targetPort: 5572
      protocol: TCP
  selector:
    component: {{ .Values.rclone.component }}
    subsystem: {{ .Values.rclone.subsystem }}

{{ with .Values.rclone.secret }}
{{- if and .enabled .vault.enabled }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  namespace: {{ $.Release.Namespace }}
  name: {{ include "ska-dlm.rclone.secret.name" $ }}
spec:
  mount: {{ .vault.mount }}
  type: {{ .vault.type }}
  path: {{ .vault.path }}
  destination:
    create: true
    name: {{ include "ska-dlm.rclone.secret.name" $ }}
    transformation:
      excludeRaw: true
{{- end }}
{{- end }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ska-dlm.fullname" . }}-rclone
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ska-dlm.rclone.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.rclone.replicas }}
  selector:
    matchLabels:
      component: {{ .Values.rclone.component }}
      subsystem: {{ .Values.rclone.subsystem }}
  template:
    metadata:
      labels:
        {{- include "ska-dlm.rclone.labels" . | indent 8 }}
    spec:
      containers:
      - name: rclone
        image: {{ .Values.rclone.image}}:{{ .Values.rclone.version }}
        imagePullPolicy: {{ .Values.rclone.imagePullPolicy }}
        command:
          - rclone
          - rcd
        {{ with .Values.rclone.secret }}
        {{- if and .enabled (not (empty .ssl_cert_name)) (not (empty .ssl_key_name)) }}
          - --rc-cert={{ .mountPoint }}/{{ .ssl_cert_name }}
          - --rc-key={{ .mountPoint }}/{{ .ssl_key_name }}
        {{- end }}
        {{- end }}
          - --rc-serve
          - --rc-addr
          - :5572
          - --rc-no-auth
        readinessProbe:
          httpGet:
            path: /
            port: 5572
          {{ with .Values.rclone.secret }}
          {{- if and .enabled (not (empty .ssl_cert_name)) (not (empty .ssl_key_name)) }}
            scheme: HTTPS
          insecureSkipVerify: true # Skip certificate verification
          {{- end }}
          {{- end }}

          periodSeconds: 5
        volumeMounts:
        {{ with .Values.rclone.secret }}
        {{- if .enabled }}
          - mountPath: {{ .mountPoint }}
            name: {{ include "ska-dlm.rclone.secret.name" $ }}
            readOnly: true
        {{- end }}
        {{- end }}

      {{ with .Values.rclone.secret }}
      {{- if .enabled }}
      volumes:
      - name: {{ include "ska-dlm.rclone.secret.name" $ }}
        secret:
            secretName: {{ include "ska-dlm.rclone.secret.name" $ }}
      {{- end }}
      {{- end }}