apiVersion: v1
kind: Service
metadata:
  name: {{ include "ska-dlm.fullname" . }}-rclone
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ska-dlm.rclone.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: tcp-rclone
      port: 80
      targetPort: 5572
      protocol: TCP
  selector:
    component: {{ .Values.rclone.component }}
    subsystem: {{ .Values.rclone.subsystem }}

{{ with .Values.rclone.secret }}
{{- if .enabled }}
{{- if .vault.enabled }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  namespace: {{ $.Release.Namespace }}
  name: {{ include "ska-dlm.rclone.secret.name" $ }}
spec:
  mount: {{ .vault.mount }}
  type: {{ .vault.type }}
  path: {{ .vault.path }}
  destination:
    create: true
    name: {{ include "ska-dlm.rclone.secret.name" $ }}
    transformation:
      excludeRaw: true
{{- else }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "ska-dlm.rclone.labels" $ | indent 4 }}
type: Opaque
data:
  {{- with .secretData | default dict }}
  {{- range $key, $value := . }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
{{- else }}
{{- if .vault.enabled }}
{{- fail "Rclone secrets can not be disabled while the vault is enabled" }}
{{- end }}
{{- end }}
{{- end }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ska-dlm.fullname" . }}-rclone
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ska-dlm.rclone.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.rclone.replicas }}
  selector:
    matchLabels:
      component: {{ .Values.rclone.component }}
      subsystem: {{ .Values.rclone.subsystem }}
  template:
    metadata:
      labels:
        {{- include "ska-dlm.rclone.labels" . | indent 8 }}
    spec:
      containers:
      - name: rclone
        image: {{ .Values.rclone.image}}:{{ .Values.rclone.version }}
        imagePullPolicy: {{ .Values.rclone.imagePullPolicy }}
        command:
          - rclone
          - rcd
          - --rc-serve
          - --rc-addr
          - :5572
          - --rc-no-auth
        readinessProbe:
          httpGet:
            path: /
            port: 5572
          periodSeconds: 5
        volumeMounts:
        {{ with .Values.rclone.secret }}
        {{- if .enabled }}
          - mountPath: {{ .mountPoint }}
            name: {{ include "ska-dlm.rclone.secret.name" $ }}
            readOnly: true
        {{- end }}
        {{- end }}
      volumes:
      - name: {{ include "ska-dlm.rclone.secret.name" $ }}
        secret:
            secretName: {{ include "ska-dlm.rclone.secret.name" $ }}