apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ska-dlm.fullname" . }}-rclone-configmap
data:
  rclone-start.sh: |-
    #!/bin/bash
    if [[ ! -f /dlm/.ssh/id_rsa.pub ]]; then
      mkdir -p /dlm/.ssh
      yes n | ssh-keygen -t rsa -b 4096 -f /dlm/.ssh/id_rsa -N '' || true
    fi
    mkdir -p /root/.ssh
    chmod 700 -R /root/.ssh
    cp -p /dlm/.ssh/id_rsa /root/.ssh/id_rsa 2>/dev/null
    eval "$(ssh-agent -s)"
    ssh-add /root/.ssh/id_rsa
    rclone \
    rcd \
    --rc-web-gui-no-open-browser \
    --rc-serve \
    --rc-addr \
    :5572 \
    --rc-no-auth \
    /