apiVersion: v1
kind: Service
metadata:
  name: {{ include "ska-dlm.name" . }}-request
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ska-dlm.request.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8002
      protocol: TCP
  selector:
    component: {{ .Values.request.component }}
    subsystem: {{ .Values.request.subsystem }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ska-dlm.name" . }}-request
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ska-dlm.request.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.request.replicas }}
  selector:
    matchLabels:
      component: {{ .Values.request.component }}
      subsystem: {{ .Values.request.subsystem }}
  template:
    metadata:
      labels:
        {{- include "ska-dlm.request.labels" . | indent 8 }}
    spec:
      containers:
      - name: request
        image: {{ .Values.request.image}}:{{ .Values.request.version }}
        imagePullPolicy: {{ .Values.request.imagePullPolicy }}
        command:
          - uvicorn
          - ska_dlm.dlm_request.dlm_request_requests:app
          - --port
          - "8002"
          # - fastapi
          # - {{ ternary "dev" "run" .Values.global.development }}
          # - src/ska_dlm/dlm_storage/dlm_storage_requests.py
          # - --port
          # - "8003"
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: 8003
        #   periodSeconds: 5
        volumeMounts:
        - name: dlm-configmap
          mountPath: "/home/ska-dlm/.dlm"
          readOnly: true
      volumes:
      - name: dlm-configmap
        configMap:
          name: {{ include "ska-dlm.name" . }}-configmap