apiVersion: v1
kind: Service
metadata:
  name: {{ include "ska-dlm.fullname" . }}-storage
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ska-dlm.storage.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8003
      protocol: TCP
  selector:
    component: {{ .Values.storage.component }}
    subsystem: {{ .Values.storage.subsystem }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ska-dlm.fullname" . }}-storage
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ska-dlm.storage.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.storage.replicas }}
  selector:
    matchLabels:
      component: {{ .Values.storage.component }}
      subsystem: {{ .Values.storage.subsystem }}
  template:
    metadata:
      labels:
        {{- include "ska-dlm.storage.labels" . | indent 8 }}
    spec:
      containers:
      - name: storage
        image: {{ .Values.storage.image}}:{{ .Values.storage.version }}
        imagePullPolicy: {{ .Values.storage.imagePullPolicy }}
        command:
        - uvicorn
        - ska_dlm.dlm_storage.dlm_storage_requests:rest
        - --host
        - "0.0.0.0"
        - --port
        - "8003"
        env:
          - name: CONFIG
            value: "/etc/storage-config.json"
        ports:
        - containerPort: 8003
          name: http-port
        readinessProbe:
          tcpSocket:
            port: http-port
          periodSeconds: 5
          initialDelaySeconds: 5
        livenessProbe:
          tcpSocket:
            port: http-port
          periodSeconds: 5
          initialDelaySeconds: 5
        volumeMounts:
        - name: dlm-configmap
          mountPath: "/home/ska-dlm/.dlm"
          readOnly: true
        - name: storage-configmap
          mountPath: "/etc/storage-config.json"
          subPath: storage-config.json
          readOnly: true
      volumes:
      - name: dlm-configmap
        configMap:
          name: {{ include "ska-dlm.fullname" . }}-configmap
      - name: storage-configmap
        configMap:
          name: {{ include "ska-dlm.fullname" . }}-storage-configmap